### PR TITLE
mask overlay

### PR DESCRIPTION
**Pull request by jwindhager**

### CODE REVIEW

**Comment by nilseling** [comment]
How big are the tiffs? Should we add them via git-lfs? In general, should we add the .mcd via git-lfs?

**Comment by jwindhager** [comment]
Close to 100mb, so yes, they should probably be added via LFS... :innocent:

Adding the mcd here would be a good idea!

**Comment by nilseling** [comment]
Cool, not sure if you can add them via a PR? If not, can you just send me the files and I'll add them.

**Comment by jwindhager** [comment]
converted the image & mask to LFS

where should we add the mcd?

**Comment by nilseling** [comment]
Hmm, maybe in data? But wait a bit - there was a weird bandwidth issues with LFS.

**Comment by jwindhager** [comment]
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

**Comment by jwindhager** [comment]
Maybe not use LFS after all?

**Comment by nilseling** [comment]
Yeah, let's forget about the .mcd. The .tiffs are fine

**Comment by votti** [comment]
Hi BBteam,

Nowadays I would recommend you to also consider DVC to keep data assets and
code in sync.

https://dvc.org/

Really easy to setup and supports lots of storage backends

https://dvc.org/doc/command-reference/remote/add

Cheers!

**Comment by jwindhager** [comment]
Thanks @votti, completely forgot about DVC! Used it a couple of years ago, but it didn't seem widely adopted back then. Will look into it again - it's still installed, after all (and probably horribly outdated...) :) Thanks again!

**Comment by nilseling** [comment]
I'm a bit lost here, @jwindhager can I merge this?

**Comment by jwindhager** [comment]
Removed LFS due to bandwith issues (see above), now mergable!

**Pull request merged**
